pipeline:
  name: test
  identifier: test
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dataops
        repoName: harness
        build:
          type: branch
          spec:
            branch: main
  stages:
    - stage:
        name: Run Python Script
        identifier: run_python_stage
        description: Clone repo and run trigger_dataflow.py
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Execute Python Script
                  identifier: run_python
                  spec:
                    image: python:3.10
                    shell: Sh
                    command: |-
                      echo "Installing dependencies if requirements.txt exists..."
                      if [ -f requirements.txt ]; then
                        pip install -r requirements.txt
                      fi

                      echo "Running Python script..."
                      python3 trigger_dataflow.py
                      echo "Python script completed successfully!"
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
